# Generated by Django 4.2.1 on 2023-05-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('hamster', models.CharField(max_length=500, null=True)),
                ('weather', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('body', models.TextField()),
            ],
        ),
    ]
