# Generated by Django 4.2 on 2023-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hamster',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weather',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
