# Generated by Django 4.2 on 2023-05-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_hamster_post_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
