# Generated by Django 4.2 on 2023-05-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgfile',
        ),
    ]
